-- RecycleConnect Seed Data
-- Run this AFTER migration.sql to populate real data
-- Safe to run multiple times (uses ON CONFLICT / DELETE + INSERT)

-- ============================================================
-- RECYCLING CENTRES (real locations across Malaysia)
-- ============================================================
DELETE FROM recycling_centres;

INSERT INTO recycling_centres (id, name, description, address, city, state, lat, lng, hours, contact, materials, category, pays_cash, reward_points, home_collection, rating) VALUES
-- Klang Valley - Petaling Jaya
(
  gen_random_uuid(),
  'IPC Recycling & Buy-Back Centre',
  'Malaysia''s first mall-based recycling centre. Earn Tack Points for every drop-off. Dedicated 10-min drop-off parking bay.',
  'Level P1 (near Ladies Parking), IPC Shopping Centre, 2 Jalan PJU 7/2, Mutiara Damansara',
  'Petaling Jaya',
  'Selangor',
  3.1557, 101.6107,
  'Daily 8am–10pm',
  '017-804 7033',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Batteries', 'Clothes', 'Cooking Oil'],
  'Buy-Back Centre',
  TRUE, TRUE, FALSE,
  4.6
),
(
  gen_random_uuid(),
  '1Recycling Centre (1RC) @ 1 Utama',
  'One-stop recycling hub at Malaysia''s first Green Mall. Earn Green Points via SuperApp.',
  'B2 Highstreet, 1 Utama Shopping Centre, 1 Lebuh Bandar Utama, Bandar Utama',
  'Petaling Jaya',
  'Selangor',
  3.1506, 101.6154,
  'Daily 10am–10pm',
  '03-7725 5788',
  ARRAY['Paper', 'Plastic', 'Metal', 'Electronics', 'Clothes'],
  'Mall Recycling Hub',
  FALSE, TRUE, FALSE,
  4.5
),
(
  gen_random_uuid(),
  'PJ Eco Recycling Plaza',
  'Community recycling plaza accepting books, stationery, e-waste, and more. Runs educational workshops.',
  'Jalan SS8/39, Sungai Way Free Trade Industrial Zone',
  'Petaling Jaya',
  'Selangor',
  3.0823, 101.6145,
  'Tue–Sun 9am–4pm (Mon closed)',
  '03-7865 8049',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Batteries', 'Clothes'],
  'Community Recycling Plaza',
  FALSE, FALSE, FALSE,
  4.3
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre SS2',
  'Tzu Chi recycling centre in SS2 Petaling Jaya. Welcomes sorted recyclable drop-offs.',
  '12 Jalan SS2/55, 47300 Petaling Jaya',
  'Petaling Jaya',
  'Selangor',
  3.1189, 101.6245,
  'Tue–Sun 8am–5pm',
  '03-7875 1234',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes', 'Batteries'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.2
),
(
  gen_random_uuid(),
  'Tropicana Gardens Mall Recycling Hub',
  'Mall-based recycling drop-off in Tropicana Gardens. Convenient for Damansara residents.',
  'Tropicana Gardens Mall, 2A Jalan PJU 3/1, Kota Damansara',
  'Petaling Jaya',
  'Selangor',
  3.1448, 101.5865,
  'Daily 10am–10pm',
  '03-7622 8855',
  ARRAY['Paper', 'Plastic', 'Metal', 'Electronics'],
  'Mall Recycling Hub',
  FALSE, FALSE, FALSE,
  4.0
),
-- Kuala Lumpur
(
  gen_random_uuid(),
  'Thanam Industry Sdn Bhd',
  'One of Malaysia''s oldest scrap metal and waste recyclers. Accepts ferrous/non-ferrous metals, plastics, papers, e-waste.',
  '631 Jalan Lima, Off Jalan Chan Sow Lin',
  'Kuala Lumpur',
  'Kuala Lumpur',
  3.1217, 101.7189,
  'Mon–Sat 8am–6pm (Sun closed)',
  '019-315 5261',
  ARRAY['Paper', 'Plastic', 'Metal', 'Electronics', 'Batteries', 'Cooking Oil'],
  'Scrap & Waste Recycler',
  TRUE, FALSE, TRUE,
  4.4
),
(
  gen_random_uuid(),
  'Tzu Chi Happy Garden Recycling Centre',
  'Buddhist Tzu Chi Foundation recycling centre. Part of their 160+ centres nationwide.',
  'Happy Garden, Jalan Lazat, Sri Petaling',
  'Kuala Lumpur',
  'Kuala Lumpur',
  3.0645, 101.6885,
  'Daily 8am–5pm',
  '03-9058 2190',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.5
),
(
  gen_random_uuid(),
  'TRASH4CASH KL & Selangor',
  'Drop-off points across KL & Selangor that pay cash for recyclables.',
  'Various locations across Kuala Lumpur',
  'Kuala Lumpur',
  'Kuala Lumpur',
  3.1390, 101.6869,
  'By appointment',
  'Instagram @trash4cashklselangor',
  ARRAY['Paper', 'Plastic', 'Metal', 'Electronics', 'Cooking Oil', 'Clothes'],
  'Buy-Back Collection',
  TRUE, FALSE, FALSE,
  4.2
),
(
  gen_random_uuid(),
  'Kuala Lumpur City Hall (DBKL) Recycling Centre',
  'DBKL-run recycling drop-off centre serving KL residents.',
  'Jalan Dewan Bahasa, 50460 Kuala Lumpur',
  'Kuala Lumpur',
  'Kuala Lumpur',
  3.1627, 101.6943,
  'Mon–Fri 8am–5pm',
  '03-2142 8891',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.8
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre KL (Jalan Ipoh)',
  'Tzu Chi Foundation recycling centre at Jalan Ipoh.',
  '61 Jalan Ipoh, 51200 Kuala Lumpur',
  'Kuala Lumpur',
  'Kuala Lumpur',
  3.1715, 101.6902,
  'Tue–Sun 8am–5pm',
  '03-4041 7522',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes', 'Batteries'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.3
),
(
  gen_random_uuid(),
  'Bangsar Shopping Centre Recycling Point',
  'Convenient recycling drop-off in Bangsar. Accepts common household recyclables.',
  'Bangsar Shopping Centre, 285 Jalan Maarof, Bangsar',
  'Kuala Lumpur',
  'Kuala Lumpur',
  3.1286, 101.6709,
  'Daily 10am–10pm',
  '03-2287 7111',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal'],
  'Mall Recycling Hub',
  FALSE, FALSE, FALSE,
  3.9
),
(
  gen_random_uuid(),
  'Setapak Recycling Centre',
  'Community recycling drop-off in Setapak. Serves the Wangsa Maju and Setapak area.',
  'Jalan Genting Kelang, 53300 Kuala Lumpur',
  'Kuala Lumpur',
  'Kuala Lumpur',
  3.1865, 101.7205,
  'Mon–Sat 9am–5pm',
  '03-4143 2211',
  ARRAY['Paper', 'Plastic', 'Metal', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.6
),
(
  gen_random_uuid(),
  'Cheras Leisure Mall Recycling Hub',
  'Mall-based recycling drop-off in Cheras. Convenient for south KL residents.',
  'Leisure Mall, 6 Jalan Manis 1, Taman Cheras',
  'Kuala Lumpur',
  'Kuala Lumpur',
  3.0746, 101.7253,
  'Daily 10am–10pm',
  '03-9133 2233',
  ARRAY['Paper', 'Plastic', 'Metal', 'Electronics', 'Glass'],
  'Mall Recycling Hub',
  FALSE, FALSE, FALSE,
  3.8
),
(
  gen_random_uuid(),
  'Batu Caves Recycling Centre',
  'Recycling drop-off centre near Batu Caves. Accepts sorted household waste.',
  'Jalan Batu Caves, 68100 Batu Caves',
  'Kuala Lumpur',
  'Kuala Lumpur',
  3.2376, 101.6839,
  'Mon–Sat 9am–5pm',
  '03-6187 5522',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
-- Putrajaya
(
  gen_random_uuid(),
  'Pusat Kitar Semula Komuniti Putrajaya',
  'Community recycling centre serving Putrajaya residents.',
  'Jalan P9b, Presint 9',
  'Putrajaya',
  'Putrajaya',
  2.9273, 101.6893,
  'Daily 8:30am–3pm',
  '03-8890 1767',
  ARRAY['Paper', 'Plastic', 'Metal', 'Electronics', 'Batteries'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  4.1
),
(
  gen_random_uuid(),
  'Alam Flora Drive Thru Recycling Centre (DTRC)',
  'Drive-thru recycling centre by Alam Flora. Cash reward given.',
  '1 Jalan P5B, Presint 20',
  'Putrajaya',
  'Putrajaya',
  2.9012, 101.6714,
  'Mon–Fri 8am–5pm, Sat 8am–1pm',
  '03-2052 7745',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Cooking Oil', 'Batteries'],
  'Drive-Thru Buy-Back',
  TRUE, FALSE, FALSE,
  4.3
),
-- Cyberjaya
(
  gen_random_uuid(),
  'Cyberjaya Recycling Centre',
  'Recycling centre serving the Cyberjaya community.',
  'Jalan Teknokrat 5, Cyber 5',
  'Cyberjaya',
  'Selangor',
  2.9237, 101.6487,
  'Mon–Sat 9am–5pm',
  '03-8318 1660',
  ARRAY['Paper', 'Plastic', 'Metal', 'Electronics', 'Cooking Oil', 'Clothes'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  4.0
),
-- Shah Alam
(
  gen_random_uuid(),
  'Pusat Kitar Semula Shah Alam (MBSA)',
  'Shah Alam City Council recycling drop-off.',
  'Jalan Platun 2/2, Seksyen 2, 40000 Shah Alam',
  'Shah Alam',
  'Selangor',
  3.0792, 101.5135,
  'Mon–Sat 8am–5pm',
  '03-5522 5581',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.9
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Shah Alam',
  'Tzu Chi recycling centre in Shah Alam.',
  '1 Jalan Serai 4, Taman Sri Muda, 40400 Shah Alam',
  'Shah Alam',
  'Selangor',
  3.0652, 101.5033,
  'Tue–Sun 8am–5pm',
  '03-5121 3022',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes', 'Batteries'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.1
),
(
  gen_random_uuid(),
  'Seksyen 7 Shah Alam Recycling Point',
  'Community recycling point in Shah Alam Seksyen 7.',
  'Jalan Sungai Burung 7/15, Seksyen 7, 40000 Shah Alam',
  'Shah Alam',
  'Selangor',
  3.0553, 101.5032,
  'Mon–Sat 8am–5pm',
  '03-5522 3344',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.7
),
(
  gen_random_uuid(),
  'Kota Kemuning Recycling Centre',
  'Community recycling drop-off in Kota Kemuning, Shah Alam.',
  'Jalan Anggerik Vanilla 31/71, Kota Kemuning, 40460 Shah Alam',
  'Shah Alam',
  'Selangor',
  3.0025, 101.5355,
  'Mon–Fri 9am–5pm',
  '03-5122 6677',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.8
),
-- Klang
(
  gen_random_uuid(),
  'Klang Municipal Council (MPK) Recycling Centre',
  'Klang municipal recycling centre.',
  'Jalan Tengku Kelana, 41000 Klang',
  'Klang',
  'Selangor',
  3.0417, 101.4471,
  'Mon–Fri 8am–5pm',
  '03-3371 2311',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.7
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Klang (Bayu Tinggi)',
  'Tzu Chi recycling centre in Bayu Tinggi, Klang.',
  '49 Lorong Sentosa 4A, Taman Bayu Tinggi, 41200 Klang',
  'Klang',
  'Selangor',
  3.0123, 101.4281,
  'Sat 9am–12pm',
  '03-3322 1144',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  3.8
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Klang (Chi Liung)',
  'Tzu Chi recycling centre in Taman Chi Liung, Klang.',
  '26 Lorong Seleguri 3, Taman Chi Liung, 41200 Klang',
  'Klang',
  'Selangor',
  3.0239, 101.4276,
  'Wed & Sat 11am–3pm',
  '03-3322 1145',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  3.7
),
(
  gen_random_uuid(),
  'Port Klang Recycling Centre',
  'Recycling centre serving Port Klang area. Accepts commercial and household waste.',
  'Jalan Pelabuhan Utara, 42000 Pelabuhan Klang',
  'Klang',
  'Selangor',
  3.0047, 101.3873,
  'Mon–Sat 8am–5pm',
  '03-3167 8890',
  ARRAY['Paper', 'Plastic', 'Metal', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.6
),
-- Subang Jaya / USJ
(
  gen_random_uuid(),
  'Subang Jaya Recycling Centre (MBSJ)',
  'Subang Jaya municipal recycling centre.',
  'Jalan SS15/4B, 47500 Subang Jaya',
  'Subang Jaya',
  'Selangor',
  3.0765, 101.5878,
  'Mon–Sat 8am–5pm',
  '03-5637 1122',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Batteries'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.9
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Subang Jaya',
  'Tzu Chi Foundation recycling centre in Subang Jaya.',
  '5 Jalan SS15/8, 47500 Subang Jaya',
  'Subang Jaya',
  'Selangor',
  3.0742, 101.5846,
  'Tue–Sun 8am–5pm',
  '03-5634 5566',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes', 'Batteries'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.1
),
(
  gen_random_uuid(),
  'USJ Taipan Recycling Point',
  'Convenient recycling drop-off in USJ Taipan.',
  'Jalan USJ 10/1, Taipan Business Centre, 47620 Subang Jaya',
  'Subang Jaya',
  'Selangor',
  3.0548, 101.5752,
  'Mon–Sat 9am–5pm',
  '03-5637 3344',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.7
),
-- Cheras / Kajang / Bangi
(
  gen_random_uuid(),
  'Kajang Recycling Centre (MPKj)',
  'Kajang municipal recycling drop-off centre.',
  'Jalan Semenyih, 43000 Kajang',
  'Kajang',
  'Selangor',
  2.9882, 101.7889,
  'Mon–Fri 8am–5pm',
  '03-8736 5522',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.7
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Cheras',
  'Tzu Chi recycling centre in Cheras, Selangor.',
  '12 Jalan C180/1, Dataran C180, 43200 Cheras',
  'Cheras',
  'Selangor',
  3.0452, 101.7752,
  'Tue–Sun 8am–5pm',
  '03-9075 1122',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes', 'Batteries'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.0
),
(
  gen_random_uuid(),
  'Bangi Recycling Centre',
  'Community recycling drop-off in Bandar Baru Bangi.',
  'Jalan Bangi, 43650 Bandar Baru Bangi',
  'Bangi',
  'Selangor',
  2.9544, 101.7678,
  'Mon–Fri 9am–5pm',
  '03-8911 5566',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.6
),
-- Ampang / Hulu Langat
(
  gen_random_uuid(),
  'Ampang Recycling Centre',
  'Community recycling centre serving Ampang area.',
  'Jalan Ampang, 68000 Ampang',
  'Ampang',
  'Selangor',
  3.1508, 101.7685,
  'Mon–Sat 8am–5pm',
  '03-4291 5566',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.6
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Ampang',
  'Tzu Chi recycling centre in Ampang.',
  '5 Jalan Mamanda 2, Ampang Point, 68000 Ampang',
  'Ampang',
  'Selangor',
  3.1501, 101.7582,
  'Tue–Sun 8am–5pm',
  '03-4270 7788',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.1
),
-- Puchong
(
  gen_random_uuid(),
  'Puchong Recycling Centre (MBPJ)',
  'Community recycling drop-off in Puchong.',
  'Jalan PUJ 3/1, 47100 Puchong',
  'Puchong',
  'Selangor',
  2.9982, 101.6135,
  'Mon–Sat 8am–5pm',
  '03-8075 1234',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.7
),
(
  gen_random_uuid(),
  'IOI Mall Puchong Recycling Hub',
  'Mall-based recycling drop-off in IOI Mall Puchong.',
  'IOI Mall, 47200 Puchong',
  'Puchong',
  'Selangor',
  2.9912, 101.6215,
  'Daily 10am–10pm',
  '03-8075 8888',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Mall Recycling Hub',
  FALSE, FALSE, FALSE,
  3.8
),
-- Rawang
(
  gen_random_uuid(),
  'Rawang Recycling Centre',
  'Community recycling centre in Rawang.',
  'Jalan Rawang, 48000 Rawang',
  'Rawang',
  'Selangor',
  3.3198, 101.5752,
  'Mon–Sat 8am–5pm',
  '03-6091 2233',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
-- Sepang / KLIA
(
  gen_random_uuid(),
  'Sepang Recycling Centre',
  'Recycling centre in Sepang. Serves KLIA and surrounding areas.',
  'Jalan KLIA 1, 64000 KLIA, Sepang',
  'Sepang',
  'Selangor',
  2.7412, 101.7068,
  'Mon–Fri 8am–5pm',
  '03-8706 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
-- Kuala Selangor
(
  gen_random_uuid(),
  'Kuala Selangor Recycling Centre',
  'Community recycling point in Kuala Selangor.',
  'Jalan Kuala Selangor, 45000 Kuala Selangor',
  'Kuala Selangor',
  'Selangor',
  3.3502, 101.2528,
  'Mon–Fri 9am–5pm',
  '03-3289 2233',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
-- Banting
(
  gen_random_uuid(),
  'Banting Recycling Centre',
  'Recycling drop-off in Banting, Kuala Langat.',
  'Jalan Sultan, 42700 Banting',
  'Banting',
  'Selangor',
  2.8198, 101.5012,
  'Mon–Sat 8am–5pm',
  '03-3187 4455',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
-- Semenyih
(
  gen_random_uuid(),
  'Semenyih Recycling Centre',
  'Community recycling drop-off in Semenyih.',
  'Jalan Semenyih, 43500 Semenyih',
  'Semenyih',
  'Selangor',
  2.9562, 101.8452,
  'Mon–Fri 9am–5pm',
  '03-8724 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
-- Penang Island
(
  gen_random_uuid(),
  'Penang Green Council MAMPAN Centre',
  'Penang''s zero-waste directory and recycling hub. Supports 5Rs.',
  'No. 1, Jalan Seri Bahari, 11600 George Town',
  'George Town',
  'Penang',
  5.4145, 100.3293,
  'Mon–Fri 8am–5pm',
  '04-250 3322',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Batteries', 'Clothes', 'Cooking Oil'],
  'Green Council Hub',
  FALSE, FALSE, FALSE,
  4.4
),
(
  gen_random_uuid(),
  'Pusat Kitar Semula Pulau Pinang',
  'Penang state recycling centre. Drop-off for household recyclables and e-waste.',
  'Jalan Sungai Dua, 11700 Gelugor',
  'George Town',
  'Penang',
  5.3553, 100.2950,
  'Tue–Sun 9am–5pm (Mon closed)',
  '04-658 4251',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics'],
  'State Recycling Centre',
  FALSE, FALSE, FALSE,
  4.0
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Education Centre Penang',
  'Tzu Chi Foundation recycling education centre in George Town.',
  '1A Lorong Lumba Kuda, 11400 George Town',
  'George Town',
  'Penang',
  5.4125, 100.3351,
  'Tue–Sun 9am–5pm',
  '04-828 7892',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes', 'Batteries'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.3
),
(
  gen_random_uuid(),
  'Excellent Recycling Centre',
  'Private recycling centre on Hutton Lane.',
  '176 Hutton Lane, 10050 George Town',
  'George Town',
  'Penang',
  5.4265, 100.3221,
  'Mon–Sat 9am–6pm',
  '04-226 1032',
  ARRAY['Paper', 'Plastic', 'Metal', 'Electronics'],
  'Scrap & Waste Recycler',
  TRUE, FALSE, FALSE,
  3.9
),
(
  gen_random_uuid(),
  'Eden Handicap Recycling Unit',
  'Social enterprise recycling centre in Bayan Lepas. Employs persons with disabilities.',
  '102-E Lengkok Kampung Jawa 2, Kawasan MIEL, 11900 Bayan Lepas',
  'Bayan Lepas',
  'Penang',
  5.2858, 100.2771,
  'Mon–Fri 8:30am–5pm',
  '04-644 2912',
  ARRAY['Paper', 'Plastic', 'Metal', 'Electronics', 'Clothes', 'Batteries'],
  'Social Enterprise',
  FALSE, FALSE, FALSE,
  4.4
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Balik Pulau',
  'Tzu Chi recycling centre serving Balik Pulau community.',
  'Jalan Balik Pulau, 11000 Balik Pulau',
  'Balik Pulau',
  'Penang',
  5.3525, 100.2345,
  'Tue–Sun 8am–12pm',
  '04-866 1122',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  3.9
),
(
  gen_random_uuid(),
  'Tanjung Bungah Recycling Point',
  'Community recycling drop-off in Tanjung Bungah.',
  'Jalan Tanjung Bungah, 11200 Tanjung Bungah',
  'Tanjung Bungah',
  'Penang',
  5.4602, 100.2815,
  'Mon–Sat 9am–5pm',
  '04-899 2233',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.6
),
-- Penang Mainland (Seberang Perai)
(
  gen_random_uuid(),
  'MM Century Sdn Bhd',
  'Total waste management and recycling in Bukit Mertajam.',
  'Plot 154(b) Lorong Perindustrian Bukit Minyak, Taman Perindustrian Bukit Minyak, 14000 Bukit Mertajam',
  'Bukit Mertajam',
  'Penang',
  5.2959, 100.4580,
  'Mon–Fri 8am–6pm',
  '017-476 8984',
  ARRAY['Paper', 'Plastic', 'Metal', 'Electronics'],
  'Scrap & Waste Recycler',
  TRUE, FALSE, TRUE,
  4.1
),
(
  gen_random_uuid(),
  'Butterworth Recycling Centre',
  'Community recycling drop-off in Butterworth.',
  'Jalan Bagan Luar, 12000 Butterworth',
  'Butterworth',
  'Penang',
  5.4122, 100.3648,
  'Mon–Sat 8am–5pm',
  '04-332 4455',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.7
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Bukit Mertajam',
  'Tzu Chi recycling centre in Bukit Mertajam.',
  '8 Jalan Damai 2, Taman Damai, 14000 Bukit Mertajam',
  'Bukit Mertajam',
  'Penang',
  5.3385, 100.4715,
  'Tue–Sun 8am–5pm',
  '04-538 1122',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.0
),
(
  gen_random_uuid(),
  'Nibong Tebal Recycling Centre',
  'Community recycling centre in Nibong Tebal.',
  'Jalan Besar, 14300 Nibong Tebal',
  'Nibong Tebal',
  'Penang',
  5.1665, 100.4765,
  'Mon–Fri 9am–5pm',
  '04-593 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
(
  gen_random_uuid(),
  'Kepala Batas Recycling Centre',
  'Community recycling drop-off in Kepala Batas.',
  'Jalan Kepala Batas, 13200 Kepala Batas',
  'Kepala Batas',
  'Penang',
  5.5156, 100.4255,
  'Mon–Sat 8am–5pm',
  '04-575 2233',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.6
),
-- Johor
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Johor Bahru',
  'Tzu Chi Foundation recycling centre in Johor Bahru.',
  '2 Jalan Maju, Taman Maju Jaya, 80400 Johor Bahru',
  'Johor Bahru',
  'Johor',
  1.4802, 103.7638,
  'Daily 8am–5pm',
  '07-332 1338',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes', 'Batteries'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.2
),
(
  gen_random_uuid(),
  'SWM Recycling Centre Pasir Gudang',
  'SWM Environment recycling drop-off in Pasir Gudang.',
  'Jalan Perusahaan 3, Kawasan Perindustrian Pasir Gudang, 81700 Pasir Gudang',
  'Pasir Gudang',
  'Johor',
  1.4585, 103.8871,
  'Mon–Fri 8am–5pm, Sat 8am–1pm',
  '07-251 2999',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass', 'Electronics'],
  'Recycling Drop-Off',
  FALSE, FALSE, FALSE,
  3.7
),
(
  gen_random_uuid(),
  'Kulai Recycling Centre',
  'Community recycling drop-off in Kulai.',
  'Jalan Seruling 2, Taman Sri Kulai, 81000 Kulai',
  'Kulai',
  'Johor',
  1.6582, 103.6058,
  'Mon–Sat 9am–5pm',
  '07-663 5521',
  ARRAY['Paper', 'Plastic', 'Metal', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Muar',
  'Tzu Chi Foundation recycling centre in Muar.',
  '188 Jalan Meriam, 84000 Muar',
  'Muar',
  'Johor',
  2.0412, 102.5582,
  'Tue–Sun 8am–5pm',
  '06-953 1122',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.0
),
(
  gen_random_uuid(),
  'Batu Pahat Recycling Centre',
  'Community recycling drop-off in Batu Pahat.',
  'Jalan Rahmat, 83000 Batu Pahat',
  'Batu Pahat',
  'Johor',
  1.8515, 102.9315,
  'Mon–Sat 8am–5pm',
  '07-434 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.7
),
(
  gen_random_uuid(),
  'Kluang Recycling Centre',
  'Community recycling centre in Kluang.',
  'Jalan Mengkibol, 86000 Kluang',
  'Kluang',
  'Johor',
  2.0332, 103.3198,
  'Mon–Sat 9am–5pm',
  '07-771 2233',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.6
),
(
  gen_random_uuid(),
  'Segamat Recycling Centre',
  'Community recycling drop-off in Segamat.',
  'Jalan Segamat, 85000 Segamat',
  'Segamat',
  'Johor',
  2.5122, 102.8152,
  'Mon–Fri 9am–5pm',
  '07-931 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
(
  gen_random_uuid(),
  'Mersing Recycling Centre',
  'Community recycling point in Mersing.',
  'Jalan Mersing, 86800 Mersing',
  'Mersing',
  'Johor',
  2.4312, 103.8412,
  'Mon–Fri 8am–5pm',
  '07-799 1122',
  ARRAY['Paper', 'Plastic', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
(
  gen_random_uuid(),
  'Pontian Recycling Centre',
  'Community recycling drop-off in Pontian.',
  'Jalan Pontian, 82000 Pontian',
  'Pontian',
  'Johor',
  1.4865, 103.3852,
  'Mon–Sat 8am–5pm',
  '07-687 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
(
  gen_random_uuid(),
  'Kota Tinggi Recycling Centre',
  'Community recycling centre in Kota Tinggi.',
  'Jalan Kota Tinggi, 81900 Kota Tinggi',
  'Kota Tinggi',
  'Johor',
  1.7356, 103.9012,
  'Mon–Fri 9am–5pm',
  '07-882 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Johor (Taman Sentosa)',
  'Tzu Chi recycling centre in Taman Sentosa, JB.',
  '68 Jalan Sutera 2, Taman Sentosa, 80150 Johor Bahru',
  'Johor Bahru',
  'Johor',
  1.4785, 103.7812,
  'Tue–Sun 8am–5pm',
  '07-331 2233',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes', 'Batteries'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.1
),
-- Melaka
(
  gen_random_uuid(),
  'SWM Recycling Centre Melaka',
  'SWM Environment recycling drop-off in Melaka.',
  'Jalan Tun Perak, 75350 Melaka',
  'Melaka',
  'Melaka',
  2.2338, 102.2496,
  'Mon–Sat 8am–5pm',
  '06-282 6472',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.8
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Melaka',
  'Tzu Chi Foundation recycling centre in Melaka.',
  '1 Jalan Putra 2, Taman Putra, 75350 Melaka',
  'Melaka',
  'Melaka',
  2.2415, 102.2653,
  'Tue–Sun 8am–5pm (Mon closed)',
  '06-284 2525',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.1
),
(
  gen_random_uuid(),
  'Alor Gajah Recycling Centre',
  'Community recycling drop-off in Alor Gajah.',
  'Jalan Alor Gajah, 78000 Alor Gajah',
  'Alor Gajah',
  'Melaka',
  2.3802, 102.2085,
  'Mon–Sat 8am–5pm',
  '06-556 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
(
  gen_random_uuid(),
  'Jasin Recycling Centre',
  'Community recycling centre in Jasin.',
  'Jalan Jasin, 77000 Jasin',
  'Jasin',
  'Melaka',
  2.3012, 102.4315,
  'Mon–Fri 9am–5pm',
  '06-529 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
(
  gen_random_uuid(),
  'Masjid Tanah Recycling Centre',
  'Community recycling drop-off in Masjid Tanah.',
  'Jalan Masjid Tanah, 78300 Masjid Tanah',
  'Masjid Tanah',
  'Melaka',
  2.3512, 102.1125,
  'Mon–Sat 8am–5pm',
  '06-384 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
-- Perak
(
  gen_random_uuid(),
  'SWM Recycling Centre Ipoh',
  'SWM Environment recycling drop-off in Ipoh.',
  'Jalan Sultan Idris Shah, 30000 Ipoh',
  'Ipoh',
  'Perak',
  4.5981, 101.0897,
  'Mon–Sat 9am–5pm',
  '05-241 5523',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.7
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Ipoh',
  'Tzu Chi Foundation recycling centre in Ipoh.',
  '12 Jalan Medan Ipoh 5, Bandar Baru Medan, 31400 Ipoh',
  'Ipoh',
  'Perak',
  4.6013, 101.0792,
  'Tue–Sun 9am–12pm',
  '05-546 5113',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.0
),
(
  gen_random_uuid(),
  'Kinta Recycling Centre',
  'Private recycling centre in Kinta, Perak.',
  'Lot 234, Jalan Industri, Kawasan Perindustrian Tasek, 31400 Ipoh',
  'Ipoh',
  'Perak',
  4.6198, 101.1055,
  'Mon–Fri 8am–5pm, Sat 8am–1pm',
  '05-545 2211',
  ARRAY['Paper', 'Plastic', 'Metal'],
  'Scrap & Waste Recycler',
  TRUE, FALSE, FALSE,
  3.9
),
(
  gen_random_uuid(),
  'Taiping Recycling Centre',
  'Community recycling drop-off in Taiping.',
  'Jalan Kota, 34000 Taiping',
  'Taiping',
  'Perak',
  4.8542, 100.7425,
  'Mon–Sat 8am–5pm',
  '05-807 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.8
),
(
  gen_random_uuid(),
  'Teluk Intan Recycling Centre',
  'Community recycling centre in Teluk Intan.',
  'Jalan Maharajalela, 36000 Teluk Intan',
  'Teluk Intan',
  'Perak',
  4.0222, 101.0215,
  'Mon–Sat 9am–5pm',
  '05-621 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.6
),
(
  gen_random_uuid(),
  'Sitiawan Recycling Centre',
  'Community recycling drop-off in Sitiawan.',
  'Jalan Sitiawan, 32000 Sitiawan',
  'Sitiawan',
  'Perak',
  4.2125, 100.6952,
  'Mon–Fri 9am–5pm',
  '05-691 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
(
  gen_random_uuid(),
  'Lumut Recycling Centre',
  'Community recycling centre in Lumut.',
  'Jalan Lumut, 32200 Lumut',
  'Lumut',
  'Perak',
  4.2322, 100.6325,
  'Mon–Sat 8am–5pm',
  '05-683 1122',
  ARRAY['Paper', 'Plastic', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
(
  gen_random_uuid(),
  'Batu Gajah Recycling Centre',
  'Community recycling drop-off in Batu Gajah.',
  'Jalan Batu Gajah, 31000 Batu Gajah',
  'Batu Gajah',
  'Perak',
  4.4685, 101.0425,
  'Mon–Fri 9am–5pm',
  '05-366 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.6
),
(
  gen_random_uuid(),
  'Kampar Recycling Centre',
  'Community recycling centre in Kampar.',
  'Jalan Kampar, 31900 Kampar',
  'Kampar',
  'Perak',
  4.3122, 101.1525,
  'Mon–Sat 9am–5pm',
  '05-465 1122',
  ARRAY['Paper', 'Plastic', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
(
  gen_random_uuid(),
  'Manjung Recycling Centre',
  'Community recycling drop-off in Manjung.',
  'Jalan Manjung, 32050 Manjung',
  'Manjung',
  'Perak',
  4.1852, 100.6585,
  'Mon–Fri 9am–5pm',
  '05-688 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
(
  gen_random_uuid(),
  'Gerik Recycling Centre',
  'Community recycling centre in Gerik, northern Perak.',
  'Jalan Gerik, 33300 Gerik',
  'Gerik',
  'Perak',
  5.4245, 101.1285,
  'Mon–Fri 8am–5pm',
  '05-791 1122',
  ARRAY['Paper', 'Plastic', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.3
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Taiping',
  'Tzu Chi recycling centre in Taiping.',
  '15 Jalan Taming Sari, 34000 Taiping',
  'Taiping',
  'Perak',
  4.8545, 100.7352,
  'Tue–Sun 8am–12pm',
  '05-808 1122',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.0
),
-- Negeri Sembilan
(
  gen_random_uuid(),
  'SWM Recycling Centre Seremban',
  'SWM Environment recycling drop-off in Seremban.',
  'Jalan Tuanku Munawir, 70000 Seremban',
  'Seremban',
  'Negeri Sembilan',
  2.7286, 101.9412,
  'Mon–Sat 9am–5pm',
  '06-767 8891',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.8
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Seremban',
  'Tzu Chi Foundation recycling centre in Seremban.',
  '117 Jalan S2 G1, Seremban 2, 70300 Seremban',
  'Seremban',
  'Negeri Sembilan',
  2.7023, 101.9371,
  'Tue–Sun 8am–5pm',
  '06-601 6018',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes', 'Batteries'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.1
),
(
  gen_random_uuid(),
  'Port Dickson Recycling Centre',
  'Community recycling centre in Port Dickson.',
  'Jalan Pantai, 71000 Port Dickson',
  'Port Dickson',
  'Negeri Sembilan',
  2.5156, 101.7964,
  'Mon–Sat 9am–5pm',
  '06-647 2230',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
(
  gen_random_uuid(),
  'Nilai Recycling Centre',
  'Community recycling drop-off in Nilai.',
  'Jalan Nilai, 71800 Nilai',
  'Nilai',
  'Negeri Sembilan',
  2.8152, 101.7952,
  'Mon–Fri 9am–5pm',
  '06-794 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.6
),
(
  gen_random_uuid(),
  'Bahau Recycling Centre',
  'Community recycling centre in Bahau.',
  'Jalan Bahau, 72100 Bahau',
  'Bahau',
  'Negeri Sembilan',
  2.8122, 102.4152,
  'Mon–Sat 8am–5pm',
  '06-454 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
(
  gen_random_uuid(),
  'Tampin Recycling Centre',
  'Community recycling drop-off in Tampin.',
  'Jalan Tampin, 73000 Tampin',
  'Tampin',
  'Negeri Sembilan',
  2.4725, 102.2325,
  'Mon–Fri 9am–5pm',
  '06-441 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Nilai',
  'Tzu Chi recycling centre in Nilai.',
  '22 Jalan BBN 1/1, Bandar Bukit Nilai, 71800 Nilai',
  'Nilai',
  'Negeri Sembilan',
  2.8125, 101.7885,
  'Tue–Sun 8am–5pm',
  '06-799 1122',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  3.9
),
-- Pahang
(
  gen_random_uuid(),
  'SWM Recycling Centre Kuantan',
  'SWM Environment recycling drop-off in Kuantan.',
  'Jalan Beserah, 25300 Kuantan',
  'Kuantan',
  'Pahang',
  3.8066, 103.3260,
  'Mon–Sat 9am–5pm',
  '09-513 8892',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.6
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Kuantan',
  'Tzu Chi Foundation recycling centre in Kuantan.',
  'B-109, Jalan Dato Wong Ah Jang, 25100 Kuantan',
  'Kuantan',
  'Pahang',
  3.8154, 103.3352,
  'Tue–Sun 8am–12pm',
  '09-515 9233',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.0
),
(
  gen_random_uuid(),
  'Cameron Highlands Recycling Centre',
  'Community recycling drop-off in Cameron Highlands.',
  'Jalan Besar, 39000 Tanah Rata, Cameron Highlands',
  'Tanah Rata',
  'Pahang',
  4.4714, 101.3769,
  'Mon–Sat 9am–4pm',
  '05-491 1136',
  ARRAY['Paper', 'Plastic', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
(
  gen_random_uuid(),
  'Temerloh Recycling Centre',
  'Community recycling centre in Temerloh.',
  'Jalan Temerloh, 28000 Temerloh',
  'Temerloh',
  'Pahang',
  3.4522, 102.4215,
  'Mon–Sat 8am–5pm',
  '09-296 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.6
),
(
  gen_random_uuid(),
  'Bentong Recycling Centre',
  'Community recycling drop-off in Bentong.',
  'Jalan Bentong, 28700 Bentong',
  'Bentong',
  'Pahang',
  3.5212, 101.9125,
  'Mon–Fri 9am–5pm',
  '09-222 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
(
  gen_random_uuid(),
  'Raub Recycling Centre',
  'Community recycling centre in Raub.',
  'Jalan Raub, 27600 Raub',
  'Raub',
  'Pahang',
  3.7912, 101.8525,
  'Mon–Sat 8am–5pm',
  '09-355 1122',
  ARRAY['Paper', 'Plastic', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
(
  gen_random_uuid(),
  'Pekan Recycling Centre',
  'Community recycling drop-off in Pekan, Pahang.',
  'Jalan Pekan, 26600 Pekan',
  'Pekan',
  'Pahang',
  3.4852, 103.3852,
  'Mon–Fri 9am–5pm',
  '09-422 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Temerloh',
  'Tzu Chi recycling centre in Temerloh.',
  '5 Jalan Kaya, 28000 Temerloh',
  'Temerloh',
  'Pahang',
  3.4485, 102.4252,
  'Tue–Sun 8am–12pm',
  '09-297 1122',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  3.9
),
-- Kedah
(
  gen_random_uuid(),
  'E-Idaman DTRC Alor Setar',
  'Drive-thru recycling centre by E-Idaman. Earn idamanXchange points.',
  'Pasar Awam Mergong, 05050 Alor Setar',
  'Alor Setar',
  'Kedah',
  6.1220, 100.3691,
  'Daily 8am–6pm',
  '04-786 4588',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Cooking Oil', 'Batteries'],
  'Drive-Thru Buy-Back',
  TRUE, TRUE, FALSE,
  4.2
),
(
  gen_random_uuid(),
  'E-Idaman DTRC Sungai Petani',
  'Drive-thru recycling centre in Sungai Petani. Cash or points via idamanXchange.',
  'Taman Tuanku Haminah, 08000 Sungai Petani',
  'Sungai Petani',
  'Kedah',
  5.6463, 100.4857,
  'Daily 8am–6pm',
  '04-786 4588',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Cooking Oil', 'Batteries'],
  'Drive-Thru Buy-Back',
  TRUE, TRUE, FALSE,
  4.1
),
(
  gen_random_uuid(),
  'E-Idaman DTRC Kulim',
  'Drive-thru recycling centre in Kulim.',
  'Pusat Komuniti Bandar, Taman Lembah Impiana, 09000 Kulim',
  'Kulim',
  'Kedah',
  5.3620, 100.5615,
  'Daily 8am–6pm',
  '04-786 4588',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Cooking Oil'],
  'Drive-Thru Buy-Back',
  TRUE, TRUE, FALSE,
  4.0
),
(
  gen_random_uuid(),
  'E-Idaman DTRC Langkawi',
  'Drive-thru recycling centre at Langkawi.',
  'Pasar Awam Kelibang, Kuah, 07000 Langkawi',
  'Langkawi',
  'Kedah',
  6.3230, 99.8461,
  'Daily 8am–6pm',
  '04-786 4588',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Cooking Oil'],
  'Drive-Thru Buy-Back',
  TRUE, TRUE, FALSE,
  4.0
),
(
  gen_random_uuid(),
  'E-Idaman DTRC Jitra',
  'Drive-thru recycling centre in Jitra, Kubang Pasu.',
  'Pekan Jitra 2, 06000 Jitra',
  'Jitra',
  'Kedah',
  6.2685, 100.4185,
  'Daily 8am–6pm',
  '04-786 4588',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Cooking Oil', 'Batteries'],
  'Drive-Thru Buy-Back',
  TRUE, TRUE, FALSE,
  4.0
),
(
  gen_random_uuid(),
  'E-Idaman DTRC UUM Sintok',
  'Drive-thru recycling centre at Universiti Utara Malaysia.',
  'Universiti Utara Malaysia, 06100 Sintok',
  'Sintok',
  'Kedah',
  6.4522, 100.5012,
  'Daily 8am–6pm',
  '04-786 4588',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Cooking Oil'],
  'Drive-Thru Buy-Back',
  TRUE, TRUE, FALSE,
  3.9
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Alor Setar',
  'Tzu Chi Foundation recycling centre in Alor Setar.',
  '22 Jalan Tunku Ibrahim, 05000 Alor Setar',
  'Alor Setar',
  'Kedah',
  6.1185, 100.3652,
  'Tue–Sun 8am–5pm',
  '04-731 1122',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.0
),
(
  gen_random_uuid(),
  'Baling Recycling Centre',
  'Community recycling drop-off in Baling.',
  'Jalan Baling, 09100 Baling',
  'Baling',
  'Kedah',
  5.6785, 100.9152,
  'Mon–Fri 9am–5pm',
  '04-473 1122',
  ARRAY['Paper', 'Plastic', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
-- Kelantan
(
  gen_random_uuid(),
  'SWM Recycling Centre Kota Bharu',
  'SWM Environment recycling drop-off in Kota Bharu.',
  'Jalan Sultan Yahya Petra, 15200 Kota Bharu',
  'Kota Bharu',
  'Kelantan',
  6.1303, 102.2371,
  'Mon–Sat 9am–5pm',
  '09-744 9123',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Kota Bharu',
  'Tzu Chi Foundation recycling point in Kota Bharu.',
  'PT 437, Jalan Sultanah Zainab, 15200 Kota Bharu',
  'Kota Bharu',
  'Kelantan',
  6.1255, 102.2477,
  'Sat–Wed 8am–12pm',
  '09-748 3322',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  3.8
),
(
  gen_random_uuid(),
  'Pasir Mas Recycling Centre',
  'Community recycling drop-off in Pasir Mas.',
  'Jalan Pasir Mas, 17000 Pasir Mas',
  'Pasir Mas',
  'Kelantan',
  6.0452, 102.1425,
  'Mon–Sat 8am–5pm',
  '09-790 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
(
  gen_random_uuid(),
  'Tumpat Recycling Centre',
  'Community recycling centre in Tumpat.',
  'Jalan Tumpat, 16200 Tumpat',
  'Tumpat',
  'Kelantan',
  6.2012, 102.1712,
  'Mon–Fri 9am–5pm',
  '09-725 1122',
  ARRAY['Paper', 'Plastic', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.3
),
(
  gen_random_uuid(),
  'Tanah Merah Recycling Centre',
  'Community recycling drop-off in Tanah Merah.',
  'Jalan Tanah Merah, 17500 Tanah Merah',
  'Tanah Merah',
  'Kelantan',
  5.8122, 102.1512,
  'Mon–Sat 8am–5pm',
  '09-955 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
(
  gen_random_uuid(),
  'Kuala Krai Recycling Centre',
  'Community recycling centre in Kuala Krai.',
  'Jalan Kuala Krai, 18000 Kuala Krai',
  'Kuala Krai',
  'Kelantan',
  5.5325, 102.2025,
  'Mon–Fri 9am–5pm',
  '09-966 1122',
  ARRAY['Paper', 'Plastic', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.3
),
-- Terengganu
(
  gen_random_uuid(),
  'SWM Recycling Centre Kuala Terengganu',
  'SWM Environment recycling drop-off in Kuala Terengganu.',
  'Jalan Sultan Ismail, 20200 Kuala Terengganu',
  'Kuala Terengganu',
  'Terengganu',
  5.3295, 103.1395,
  'Mon–Sat 9am–5pm',
  '09-622 3344',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Kuala Terengganu',
  'Tzu Chi Foundation recycling centre in Kuala Terengganu.',
  'Lot 2418, Jalan Batu Buruk, 20400 Kuala Terengganu',
  'Kuala Terengganu',
  'Terengganu',
  5.3190, 103.1458,
  'Tue–Sun 8am–12pm',
  '09-622 1121',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  3.9
),
(
  gen_random_uuid(),
  'Kemaman Recycling Centre',
  'Community recycling drop-off in Kemaman.',
  'Jalan Kemaman, 24000 Kemaman',
  'Kemaman',
  'Terengganu',
  4.2352, 103.4255,
  'Mon–Sat 8am–5pm',
  '09-859 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
(
  gen_random_uuid(),
  'Dungun Recycling Centre',
  'Community recycling centre in Dungun.',
  'Jalan Dungun, 23000 Dungun',
  'Dungun',
  'Terengganu',
  4.7812, 103.4215,
  'Mon–Fri 9am–5pm',
  '09-848 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
(
  gen_random_uuid(),
  'Besut Recycling Centre',
  'Community recycling drop-off in Besut.',
  'Jalan Besut, 22200 Besut',
  'Besut',
  'Terengganu',
  5.8312, 102.5512,
  'Mon–Sat 8am–5pm',
  '09-695 1122',
  ARRAY['Paper', 'Plastic', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
(
  gen_random_uuid(),
  'Marang Recycling Centre',
  'Community recycling centre in Marang.',
  'Jalan Marang, 21600 Marang',
  'Marang',
  'Terengganu',
  5.2012, 103.2012,
  'Mon–Fri 9am–5pm',
  '09-618 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.3
),
-- Perlis
(
  gen_random_uuid(),
  'E-Idaman DTRC Kangar',
  'Drive-thru recycling centre at Pasar Awam Sena.',
  'Pasar Awam Sena, 01000 Kangar',
  'Kangar',
  'Perlis',
  6.4328, 100.1976,
  'Daily 8am–6pm',
  '04-786 4588',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Cooking Oil', 'Batteries'],
  'Drive-Thru Buy-Back',
  TRUE, TRUE, FALSE,
  4.0
),
(
  gen_random_uuid(),
  'E-Idaman DTRC Arau',
  'Drive-thru recycling centre at Pasar Awam Arau.',
  'Pasar Awam Arau, 02600 Arau',
  'Arau',
  'Perlis',
  6.4452, 100.2734,
  'Daily 8am–6pm',
  '04-786 4588',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Cooking Oil', 'Batteries'],
  'Drive-Thru Buy-Back',
  TRUE, TRUE, FALSE,
  4.0
),
(
  gen_random_uuid(),
  'Kangar Municipal Recycling Centre',
  'Community recycling drop-off in Kangar town.',
  'Jalan Kangar, 01000 Kangar',
  'Kangar',
  'Perlis',
  6.4385, 100.2012,
  'Mon–Sat 8am–5pm',
  '04-976 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
-- Sabah
(
  gen_random_uuid(),
  'SWM Recycling Centre Kota Kinabalu',
  'SWM Environment recycling drop-off in Kota Kinabalu.',
  'Jalan Lintas, 88300 Kota Kinabalu',
  'Kota Kinabalu',
  'Sabah',
  5.9561, 116.0740,
  'Mon–Sat 8am–5pm',
  '088-238 995',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.9
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Kota Kinabalu',
  'Tzu Chi Foundation recycling centre in KK.',
  'Lot 7, Jalan Kolam, 88300 Kota Kinabalu',
  'Kota Kinabalu',
  'Sabah',
  5.9612, 116.0801,
  'Tue–Sun 8am–5pm (Mon closed)',
  '088-232 112',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes', 'Batteries'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.2
),
(
  gen_random_uuid(),
  'Sandakan Recycling Centre',
  'Community recycling drop-off in Sandakan.',
  'Jalan Bunga, 90000 Sandakan',
  'Sandakan',
  'Sabah',
  5.8500, 118.0425,
  'Mon–Fri 8am–5pm',
  '089-213 441',
  ARRAY['Paper', 'Plastic', 'Metal', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.6
),
(
  gen_random_uuid(),
  'Tawau Recycling Centre',
  'Community recycling drop-off in Tawau.',
  'Jalan Haji Karim, 91000 Tawau',
  'Tawau',
  'Sabah',
  4.2498, 117.8913,
  'Mon–Sat 8am–5pm',
  '089-751 552',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
(
  gen_random_uuid(),
  'Lahad Datu Recycling Centre',
  'Community recycling centre in Lahad Datu.',
  'Jalan Lahad Datu, 91100 Lahad Datu',
  'Lahad Datu',
  'Sabah',
  5.0312, 118.3215,
  'Mon–Fri 8am–5pm',
  '089-881 1122',
  ARRAY['Paper', 'Plastic', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
(
  gen_random_uuid(),
  'Kudat Recycling Centre',
  'Community recycling drop-off in Kudat.',
  'Jalan Kudat, 89050 Kudat',
  'Kudat',
  'Sabah',
  6.8875, 116.8452,
  'Mon–Sat 8am–5pm',
  '088-611 1122',
  ARRAY['Paper', 'Plastic', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.3
),
(
  gen_random_uuid(),
  'Keningau Recycling Centre',
  'Community recycling centre in Keningau.',
  'Jalan Keningau, 89000 Keningau',
  'Keningau',
  'Sabah',
  5.3312, 116.1612,
  'Mon–Fri 9am–5pm',
  '087-331 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
(
  gen_random_uuid(),
  'Semporna Recycling Centre',
  'Community recycling drop-off in Semporna.',
  'Jalan Semporna, 91308 Semporna',
  'Semporna',
  'Sabah',
  4.4812, 118.6112,
  'Mon–Fri 8am–5pm',
  '089-782 1122',
  ARRAY['Paper', 'Plastic', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.2
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Sandakan',
  'Tzu Chi recycling centre in Sandakan.',
  '5 Jalan Pasar, 90000 Sandakan',
  'Sandakan',
  'Sabah',
  5.8425, 118.0385,
  'Tue–Sun 8am–5pm',
  '089-221 1122',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  3.9
),
-- Sarawak
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Kuching',
  'Tzu Chi Foundation recycling centre in Kuching.',
  'Lot 371, Jalan Tun Jugah, 93350 Kuching',
  'Kuching',
  'Sarawak',
  1.5545, 110.3490,
  'Tue–Sun 8am–5pm (Mon closed)',
  '082-457 722',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes', 'Batteries'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.2
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Sibu',
  'Tzu Chi recycling centre in Sibu at Rejang Park.',
  'Lot 1605, Lorong Rejang Park 14, Jalan Simpoh, 96000 Sibu',
  'Sibu',
  'Sarawak',
  2.3103, 111.8390,
  'Mon–Sat 8am–5pm',
  '084-345 121',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  4.0
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Miri',
  'Tzu Chi recycling centre in Miri.',
  'Lot 296, Jalan Chong Choon, Krokop, 98000 Miri',
  'Miri',
  'Sarawak',
  4.4192, 114.0056,
  'Tue & Fri 8:30am–11:30am, Wed 7pm–9pm',
  '085-435 552',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  3.9
),
(
  gen_random_uuid(),
  'Bintulu Recycling Centre',
  'Community recycling centre in Bintulu.',
  'Jalan Bintulu, 97000 Bintulu',
  'Bintulu',
  'Sarawak',
  3.1712, 113.0412,
  'Mon–Sat 8am–5pm',
  '086-331 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.7
),
(
  gen_random_uuid(),
  'Samarahan Recycling Centre',
  'Community recycling drop-off in Kota Samarahan.',
  'Jalan Samarahan, 94300 Kota Samarahan',
  'Kota Samarahan',
  'Sarawak',
  1.4612, 110.4812,
  'Mon–Fri 9am–5pm',
  '082-671 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.5
),
(
  gen_random_uuid(),
  'Sri Aman Recycling Centre',
  'Community recycling centre in Sri Aman.',
  'Jalan Sri Aman, 95000 Sri Aman',
  'Sri Aman',
  'Sarawak',
  1.2355, 111.4612,
  'Mon–Fri 8am–5pm',
  '083-321 1122',
  ARRAY['Paper', 'Plastic', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.4
),
(
  gen_random_uuid(),
  'Limbang Recycling Centre',
  'Community recycling drop-off in Limbang.',
  'Jalan Limbang, 98700 Limbang',
  'Limbang',
  'Sarawak',
  4.7512, 115.0112,
  'Mon–Sat 8am–5pm',
  '085-211 1122',
  ARRAY['Paper', 'Plastic', 'Metal'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.3
),
(
  gen_random_uuid(),
  'Tzu Chi Recycling Centre Bintulu',
  'Tzu Chi recycling centre in Bintulu.',
  '22 Jalan Abang Galau, 97000 Bintulu',
  'Bintulu',
  'Sarawak',
  3.1785, 113.0352,
  'Tue–Sun 8am–5pm',
  '086-332 1122',
  ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'],
  'NGO Recycling Centre',
  FALSE, FALSE, FALSE,
  3.9
),
(
  gen_random_uuid(),
  'Miri City Recycling Point',
  'Miri City Council recycling drop-off.',
  'Jalan Miri, 98000 Miri',
  'Miri',
  'Sarawak',
  4.3925, 113.9852,
  'Mon–Sat 8am–5pm',
  '085-422 1122',
  ARRAY['Paper', 'Plastic', 'Metal', 'Glass', 'Electronics'],
  'Community Recycling Centre',
  FALSE, FALSE, FALSE,
  3.6
);

,
(gen_random_uuid(), 'Tzu Chi Recycling Centre Penang (Jalan Perak)', 'Tzu Chi recycling point at Jalan Perak, Penang.', '20 Jalan Perak, 10150 George Town', 'George Town', 'Penang', 5.4192, 100.3285, 'Tue–Sun 8am–12pm', '04-261 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 4.0),
(gen_random_uuid(), 'Seberang Jaya Recycling Centre', 'Community recycling centre in Seberang Jaya.', 'Jalan Seberang Jaya, 13700 Perai', 'Perai', 'Penang', 5.3925, 100.4012, 'Mon–Sat 8am–5pm', '04-397 1122', ARRAY['Paper', 'Plastic', 'Metal', 'Glass'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.6),
(gen_random_uuid(), 'Simpang Ampat Recycling Centre', 'Community recycling drop-off in Simpang Ampat.', 'Jalan Simpang Ampat, 14100 Simpang Ampat', 'Simpang Ampat', 'Penang', 5.2812, 100.4852, 'Mon–Fri 9am–5pm', '04-588 1122', ARRAY['Paper', 'Plastic', 'Metal'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.5),
(gen_random_uuid(), 'Parit Buntar Recycling Centre', 'Community recycling centre in Parit Buntar, Perak.', 'Jalan Parit Buntar, 34200 Parit Buntar', 'Parit Buntar', 'Perak', 5.1215, 100.4912, 'Mon–Sat 8am–5pm', '05-716 1122', ARRAY['Paper', 'Plastic', 'Metal', 'Glass'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.5),
(gen_random_uuid(), 'Selama Recycling Centre', 'Community recycling drop-off in Selama, Perak.', 'Jalan Selama, 34100 Selama', 'Selama', 'Perak', 5.2215, 100.7112, 'Mon–Fri 9am–5pm', '05-839 1122', ARRAY['Paper', 'Plastic', 'Metal'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.3),
(gen_random_uuid(), 'Kuala Kangsar Recycling Centre', 'Community recycling centre in Kuala Kangsar.', 'Jalan Kuala Kangsar, 33000 Kuala Kangsar', 'Kuala Kangsar', 'Perak', 4.7712, 100.9412, 'Mon–Sat 8am–5pm', '05-776 1122', ARRAY['Paper', 'Plastic', 'Metal', 'Glass'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.6),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Kuala Kangsar', 'Tzu Chi recycling centre in Kuala Kangsar.', '8 Jalan Kangsar, 33000 Kuala Kangsar', 'Kuala Kangsar', 'Perak', 4.7685, 100.9352, 'Tue–Sun 8am–12pm', '05-777 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.9),
(gen_random_uuid(), 'Tanjung Malim Recycling Centre', 'Community recycling centre in Tanjung Malim.', 'Jalan Tanjung Malim, 35900 Tanjung Malim', 'Tanjung Malim', 'Perak', 3.6812, 101.5215, 'Mon–Fri 9am–5pm', '05-459 1122', ARRAY['Paper', 'Plastic', 'Metal', 'Glass'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.5),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Batu Pahat', 'Tzu Chi recycling centre in Batu Pahat.', '15 Jalan Zabedah, 83000 Batu Pahat', 'Batu Pahat', 'Johor', 1.8485, 102.9352, 'Tue–Sun 8am–5pm', '07-435 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.9),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Kluang', 'Tzu Chi recycling centre in Kluang.', '30 Jalan Sultanah, 86000 Kluang', 'Kluang', 'Johor', 2.0302, 103.3252, 'Tue–Sun 8am–12pm', '07-772 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.8),
(gen_random_uuid(), 'Tangkak Recycling Centre', 'Community recycling centre in Tangkak.', 'Jalan Tangkak, 84900 Tangkak', 'Tangkak', 'Johor', 2.2712, 102.5512, 'Mon–Sat 8am–5pm', '06-978 1122', ARRAY['Paper', 'Plastic', 'Metal', 'Glass'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.4),
(gen_random_uuid(), 'Yong Peng Recycling Centre', 'Community recycling drop-off in Yong Peng.', 'Jalan Yong Peng, 83700 Yong Peng', 'Yong Peng', 'Johor', 2.0112, 103.0612, 'Mon–Fri 9am–5pm', '07-467 1122', ARRAY['Paper', 'Plastic', 'Metal'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.4),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Muar II', 'Tzu Chi recycling centre in Muar (Jalan Petri).', '15 Jalan Petri, 84000 Muar', 'Muar', 'Johor', 2.0385, 102.5625, 'Tue–Sun 8am–5pm', '06-954 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 4.0),
(gen_random_uuid(), 'Labis Recycling Centre', 'Community recycling centre in Labis.', 'Jalan Labis, 85300 Labis', 'Labis', 'Johor', 2.3812, 103.0215, 'Mon–Fri 8am–5pm', '07-759 1122', ARRAY['Paper', 'Plastic', 'Metal'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.3),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Kedah (Sungai Petani)', 'Tzu Chi recycling centre in Sungai Petani.', '22 Jalan Petri, 08000 Sungai Petani', 'Sungai Petani', 'Kedah', 5.6412, 100.4825, 'Tue–Sun 8am–5pm', '04-422 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.9),
(gen_random_uuid(), 'Yan Recycling Centre', 'Community recycling centre in Yan, Kedah.', 'Jalan Yan, 06900 Yan', 'Yan', 'Kedah', 5.8012, 100.3712, 'Mon–Fri 9am–5pm', '04-719 1122', ARRAY['Paper', 'Plastic', 'Metal'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.3),
(gen_random_uuid(), 'Pendang Recycling Centre', 'Community recycling drop-off in Pendang.', 'Jalan Pendang, 06700 Pendang', 'Pendang', 'Kedah', 5.9912, 100.4712, 'Mon–Sat 8am–5pm', '04-759 1122', ARRAY['Paper', 'Plastic', 'Metal', 'Glass'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.4),
(gen_random_uuid(), 'Kubang Pasu Recycling Centre', 'Community recycling centre in Kubang Pasu.', 'Jalan Kubang Pasu, 06000 Jitra', 'Jitra', 'Kedah', 6.2612, 100.4212, 'Mon–Fri 9am–5pm', '04-917 1122', ARRAY['Paper', 'Plastic', 'Metal', 'Glass'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.5),
(gen_random_uuid(), 'Kota Sarang Semut Recycling Centre', 'Community recycling drop-off in Kota Sarang Semut, Kedah.', 'Jalan Kota Sarang Semut, 06800 Kota Sarang Semut', 'Kota Sarang Semut', 'Kedah', 6.0512, 100.7212, 'Mon–Sat 8am–5pm', '04-788 1122', ARRAY['Paper', 'Plastic', 'Metal'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.3),
(gen_random_uuid(), 'Jerantut Recycling Centre', 'Community recycling centre in Jerantut, Pahang.', 'Jalan Jerantut, 27000 Jerantut', 'Jerantut', 'Pahang', 3.9312, 102.3612, 'Mon–Sat 8am–5pm', '09-266 1122', ARRAY['Paper', 'Plastic', 'Metal', 'Glass'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.5),
(gen_random_uuid(), 'Rompin Recycling Centre', 'Community recycling drop-off in Rompin.', 'Jalan Rompin, 26800 Rompin', 'Rompin', 'Pahang', 2.7112, 103.4912, 'Mon–Fri 9am–5pm', '09-414 1122', ARRAY['Paper', 'Plastic', 'Metal'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.3),
(gen_random_uuid(), 'Maran Recycling Centre', 'Community recycling centre in Maran, Pahang.', 'Jalan Maran, 26500 Maran', 'Maran', 'Pahang', 3.5812, 102.7712, 'Mon–Fri 8am–5pm', '09-477 1122', ARRAY['Paper', 'Plastic', 'Metal'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.4),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Pahang (Bentong)', 'Tzu Chi recycling centre in Bentong.', '10 Jalan Bentong, 28700 Bentong', 'Bentong', 'Pahang', 3.5185, 101.9085, 'Tue–Sun 8am–12pm', '09-223 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.8),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Terengganu (Kemaman)', 'Tzu Chi recycling centre in Kemaman.', '5 Jalan Kemaman, 24000 Kemaman', 'Kemaman', 'Terengganu', 4.2312, 103.4225, 'Tue–Sun 8am–12pm', '09-860 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.8),
(gen_random_uuid(), 'Kuala Berang Recycling Centre', 'Community recycling centre in Kuala Berang, Terengganu.', 'Jalan Kuala Berang, 21700 Kuala Berang', 'Kuala Berang', 'Terengganu', 5.0712, 103.0012, 'Mon–Sat 8am–5pm', '09-681 1122', ARRAY['Paper', 'Plastic', 'Metal', 'Glass'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.4),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Kelantan (Pasir Mas)', 'Tzu Chi recycling centre in Pasir Mas.', '8 Jalan Pasir Mas, 17000 Pasir Mas', 'Pasir Mas', 'Kelantan', 6.0412, 102.1385, 'Tue–Sun 8am–12pm', '09-791 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.7),
(gen_random_uuid(), 'Gua Musang Recycling Centre', 'Community recycling centre in Gua Musang, Kelantan.', 'Jalan Gua Musang, 18300 Gua Musang', 'Gua Musang', 'Kelantan', 4.8812, 101.9712, 'Mon–Fri 9am–5pm', '09-912 1122', ARRAY['Paper', 'Plastic', 'Metal'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.3),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Nilai II', 'Tzu Chi recycling centre in Nilai (Bandar Baru Nilai).', '30 Jalan BBN 2/2, Bandar Baru Nilai, 71800 Nilai', 'Nilai', 'Negeri Sembilan', 2.8085, 101.7825, 'Tue–Sun 8am–5pm', '06-798 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.9),
(gen_random_uuid(), 'Jelebu Recycling Centre', 'Community recycling centre in Jelebu, N.Sembilan.', 'Jalan Jelebu, 71600 Kuala Klawang', 'Kuala Klawang', 'Negeri Sembilan', 2.9912, 102.0512, 'Mon–Fri 9am–5pm', '06-613 1122', ARRAY['Paper', 'Plastic', 'Metal'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.3),
(gen_random_uuid(), 'Rembau Recycling Centre', 'Community recycling drop-off in Rembau.', 'Jalan Rembau, 71300 Rembau', 'Rembau', 'Negeri Sembilan', 2.5912, 102.0912, 'Mon–Sat 8am–5pm', '06-685 1122', ARRAY['Paper', 'Plastic', 'Metal', 'Glass'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.4),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Sabah (Penampang)', 'Tzu Chi recycling centre in Penampang, Sabah.', '5 Jalan Penampang, 89500 Penampang', 'Penampang', 'Sabah', 5.9185, 116.1152, 'Tue–Sun 8am–5pm', '088-721 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.9),
(gen_random_uuid(), 'Ranau Recycling Centre', 'Community recycling centre in Ranau, Sabah.', 'Jalan Ranau, 89300 Ranau', 'Ranau', 'Sabah', 5.9512, 116.6612, 'Mon–Fri 8am–5pm', '088-878 1122', ARRAY['Paper', 'Plastic', 'Metal'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.3),
(gen_random_uuid(), 'Beaufort Recycling Centre', 'Community recycling drop-off in Beaufort, Sabah.', 'Jalan Beaufort, 89800 Beaufort', 'Beaufort', 'Sabah', 5.3412, 115.7412, 'Mon–Fri 9am–5pm', '087-211 1122', ARRAY['Paper', 'Plastic', 'Metal'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.2),
(gen_random_uuid(), 'Tawau Tzu Chi Recycling II', 'Tzu Chi recycling centre in Tawau (Jalan Haji Karim).', '2 Jalan Haji Karim, 91000 Tawau', 'Tawau', 'Sabah', 4.2452, 117.8885, 'Tue–Sun 8am–5pm', '089-752 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.8),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Sarawak (Miri II)', 'Tzu Chi recycling centre in Miri (Jalan Krokop).', '18 Jalan Krokop, 98000 Miri', 'Miri', 'Sarawak', 4.4225, 114.0085, 'Tue–Sun 8am–5pm', '085-436 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.9),
(gen_random_uuid(), 'Kapit Recycling Centre', 'Community recycling centre in Kapit, Sarawak.', 'Jalan Kapit, 96800 Kapit', 'Kapit', 'Sarawak', 2.0112, 112.9412, 'Mon–Fri 9am–5pm', '084-796 1122', ARRAY['Paper', 'Plastic', 'Metal'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.2),
(gen_random_uuid(), 'Mukah Recycling Centre', 'Community recycling drop-off in Mukah, Sarawak.', 'Jalan Mukah, 96400 Mukah', 'Mukah', 'Sarawak', 2.8912, 112.0912, 'Mon–Sat 8am–5pm', '084-871 1122', ARRAY['Paper', 'Plastic', 'Metal', 'Glass'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.3),
(gen_random_uuid(), 'Lawas Recycling Centre', 'Community recycling centre in Lawas, Sarawak.', 'Jalan Lawas, 98850 Lawas', 'Lawas', 'Sarawak', 4.8512, 115.4112, 'Mon–Fri 9am–5pm', '085-283 1122', ARRAY['Paper', 'Plastic', 'Metal'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.2),
(gen_random_uuid(), 'Perlis Tzu Chi Recycling', 'Tzu Chi recycling point in Kangar, Perlis.', '5 Jalan Kangar, 01000 Kangar', 'Kangar', 'Perlis', 6.4352, 100.1952, 'Tue–Sun 8am–12pm', '04-977 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE,   3.8),
(gen_random_uuid(), 'Hulu Selangor Recycling Centre', 'Community recycling centre in Hulu Selangor.', 'Jalan Hulu Selangor, 44000 Kuala Kubu Bharu', 'Kuala Kubu Bharu', 'Selangor', 3.5612, 101.6512, 'Mon–Fri 9am–5pm', '03-6064 1122', ARRAY['Paper', 'Plastic', 'Metal', 'Glass'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.4),
(gen_random_uuid(), 'Sabak Bernam Recycling Centre', 'Community recycling drop-off in Sabak Bernam.', 'Jalan Sabak Bernam, 45200 Sabak Bernam', 'Sabak Bernam', 'Selangor', 3.7712, 100.9812, 'Mon–Sat 8am–5pm', '03-3224 1122', ARRAY['Paper', 'Plastic', 'Metal'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.3),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Kajang', 'Tzu Chi recycling centre in Kajang.', '15 Jalan Kajang, 43000 Kajang', 'Kajang', 'Selangor', 2.9852, 101.7852, 'Tue–Sun 8am–5pm', '03-8737 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 4.0),
(gen_random_uuid(), 'Dengkil Recycling Centre', 'Community recycling centre in Dengkil.', 'Jalan Dengkil, 43800 Dengkil', 'Dengkil', 'Selangor', 2.8612, 101.6812, 'Mon–Fri 9am–5pm', '03-8922 1122', ARRAY['Paper', 'Plastic', 'Metal'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.3),
(gen_random_uuid(), 'Batang Kali Recycling Centre', 'Community recycling drop-off in Batang Kali.', 'Jalan Batang Kali, 44300 Batang Kali', 'Batang Kali', 'Selangor', 3.4612, 101.5215, 'Mon–Sat 8am–5pm', '03-6034 1122', ARRAY['Paper', 'Plastic', 'Metal', 'Glass'], 'Community Recycling Centre', FALSE, FALSE, FALSE, 3.4),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Seremban II', 'Tzu Chi recycling centre in Seremban (Rasah).', '2 Jalan Rasah, 70300 Seremban', 'Seremban', 'Negeri Sembilan', 2.7252, 101.9485, 'Tue–Sun 8am–5pm', '06-762 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 4.0),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Melaka (Jasin)', 'Tzu Chi recycling centre in Jasin.', '5 Jalan Jasin, 77000 Jasin', 'Jasin', 'Melaka', 2.2985, 102.4285, 'Tue–Sun 8am–12pm', '06-530 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.8),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Kedah (Kulim)', 'Tzu Chi recycling centre in Kulim.', '12 Jalan Kulim, 09000 Kulim', 'Kulim', 'Kedah', 5.3585, 100.5585, 'Tue–Sun 8am–5pm', '04-495 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.9),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Kelantan (Tumpat)', 'Tzu Chi recycling centre in Tumpat.', '8 Jalan Tumpat, 16200 Tumpat', 'Tumpat', 'Kelantan', 6.1985, 102.1685, 'Tue–Sun 8am–12pm', '09-726 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.6),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Terengganu (Besut)', 'Tzu Chi recycling centre in Besut.', '10 Jalan Besut, 22200 Besut', 'Besut', 'Terengganu', 5.8285, 102.5485, 'Tue–Sun 8am–12pm', '09-696 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.7),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Perlis (Kangar)', 'Tzu Chi recycling centre in Kangar.', '2 Jalan Kangar, 01000 Kangar', 'Kangar', 'Perlis', 6.4385, 100.1925, 'Tue–Sun 8am–12pm', '04-978 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.8),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Sabah (Keningau)', 'Tzu Chi recycling centre in Keningau.', '5 Jalan Keningau, 89000 Keningau', 'Keningau', 'Sabah', 5.3285, 116.1585, 'Tue–Sun 8am–5pm', '087-332 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.7),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Sabah (Tawau II)', 'Tzu Chi recycling centre in Tawau (Jalan Utara).', '30 Jalan Utara, 91000 Tawau', 'Tawau', 'Sabah', 4.2525, 117.8952, 'Tue–Sun 8am–5pm', '089-753 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.8),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Sarawak (Kuching II)', 'Tzu Chi recycling centre in Kuching (Jalan Batu Kawa).', '25 Jalan Batu Kawa, 93250 Kuching', 'Kuching', 'Sarawak', 1.5425, 110.3212, 'Tue–Sun 8am–5pm', '082-458 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 4.1),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Sarawak (Bintulu II)', 'Tzu Chi recycling centre in Bintulu (Jalan Tun Hussein Onn).', '15 Jalan Tun Hussein Onn, 97000 Bintulu', 'Bintulu', 'Sarawak', 3.1712, 113.0385, 'Tue–Sun 8am–5pm', '086-333 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.9),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Sabah (Lahad Datu)', 'Tzu Chi recycling centre in Lahad Datu.', '8 Jalan Lahad Datu, 91100 Lahad Datu', 'Lahad Datu', 'Sabah', 5.0285, 118.3185, 'Tue–Sun 8am–5pm', '089-882 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.7),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Johor (Segamat)', 'Tzu Chi recycling centre in Segamat.', '15 Jalan Segamat, 85000 Segamat', 'Segamat', 'Johor', 2.5085, 102.8125, 'Tue–Sun 8am–5pm', '07-932 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.8),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Perak (Sitiawan)', 'Tzu Chi recycling centre in Sitiawan.', '8 Jalan Sitiawan, 32000 Sitiawan', 'Sitiawan', 'Perak', 4.2085, 100.6912, 'Tue–Sun 8am–12pm', '05-692 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.7),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Perak (Teluk Intan)', 'Tzu Chi recycling centre in Teluk Intan.', '20 Jalan Teluk Intan, 36000 Teluk Intan', 'Teluk Intan', 'Perak', 4.0252, 101.0252, 'Tue–Sun 8am–12pm', '05-622 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.7),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Pahang (Raub)', 'Tzu Chi recycling centre in Raub.', '5 Jalan Raub, 27600 Raub', 'Raub', 'Pahang', 3.7885, 101.8485, 'Tue–Sun 8am–12pm', '09-356 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.6),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Negeri Sembilan (Port Dickson)', 'Tzu Chi recycling centre in Port Dickson.', '12 Jalan Port Dickson, 71000 Port Dickson', 'Port Dickson', 'Negeri Sembilan', 2.5185, 101.7925, 'Tue–Sun 8am–5pm', '06-648 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.7),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Kedah (Langkawi)', 'Tzu Chi recycling centre in Langkawi.', '5 Jalan Kuah, 07000 Langkawi', 'Langkawi', 'Kedah', 6.3212, 99.8425, 'Tue–Sun 8am–5pm', '04-967 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.8),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Johor (Pontian)', 'Tzu Chi recycling centre in Pontian.', '8 Jalan Pontian, 82000 Pontian', 'Pontian', 'Johor', 1.4825, 103.3825, 'Tue–Sun 8am–5pm', '07-688 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.6),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Kelantan (Tanah Merah)', 'Tzu Chi recycling centre in Tanah Merah.', '10 Jalan Tanah Merah, 17500 Tanah Merah', 'Tanah Merah', 'Kelantan', 5.8085, 102.1485, 'Tue–Sun 8am–12pm', '09-956 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.6),
(gen_random_uuid(), 'Tzu Chi Recycling Centre Sabah (Ranau)', 'Tzu Chi recycling centre in Ranau.', '3 Jalan Ranau, 89300 Ranau', 'Ranau', 'Sabah', 5.9485, 116.6585, 'Tue–Sun 8am–5pm', '088-879 1122', ARRAY['Paper', 'Plastic', 'Glass', 'Metal', 'Electronics', 'Clothes'], 'NGO Recycling Centre', FALSE, FALSE, FALSE, 3.7)
;

-- ============================================================
-- REWARDS (redeemable with Eco Points)
-- ============================================================
DELETE FROM rewards;

INSERT INTO rewards (id, name, description, eco_points_cost, category, available) VALUES
(gen_random_uuid(), 'Recycled Tote Bag', 'Eco-friendly tote bag made from recycled plastic bottles. Strong, washable, and foldable.', 150, 'Eco Product', TRUE),
(gen_random_uuid(), 'Bamboo Toothbrush Set', 'Set of 4 biodegradable bamboo toothbrushes. Zero plastic, compostable handles.', 100, 'Eco Product', TRUE),
(gen_random_uuid(), 'Stainless Steel Straw Set', 'Set of 4 stainless steel straws with cleaning brush. Reusable and portable.', 120, 'Eco Product', TRUE),
(gen_random_uuid(), 'Beeswax Food Wraps (3pk)', 'Reusable beeswax wraps to replace plastic cling film. Set of 3 assorted sizes.', 200, 'Eco Product', TRUE),
(gen_random_uuid(), 'Recycled Notebook', 'A5 notebook made from 100% post-consumer recycled paper. 80 pages, kraft cover.', 80, 'Stationery', TRUE),
(gen_random_uuid(), 'Seed Bomb Pack (5pk)', 'Throw-and-grow seed bombs with native Malaysian wildflowers. Perfect for balcony gardens.', 100, 'Eco Product', TRUE),
(gen_random_uuid(), 'Compostable Phone Case', 'Plant-based phone case that fully composts. Fits iPhone & Samsung models.', 250, 'Accessory', TRUE),
(gen_random_uuid(), 'Solar Power Bank (5000mAh)', 'Compact solar-powered charger for your devices. Perfect for outdoor use.', 500, 'Tech', TRUE),
(gen_random_uuid(), 'RM5 GrabFood Voucher', 'Redeem RM5 off your next GrabFood order. One-time use.', 300, 'Voucher', TRUE),
(gen_random_uuid(), 'RM10 Touch n Go eWallet Credit', 'Top up your Touch n Go eWallet with RM10 credit.', 500, 'Voucher', TRUE),
(gen_random_uuid(), 'Reusable Water Bottle', 'Stainless steel vacuum-insulated water bottle (500ml). Keeps drinks cold 24hrs or hot 12hrs.', 350, 'Eco Product', TRUE),
(gen_random_uuid(), 'Eco Lunch Box Set', 'Bamboo fibre lunch box with carry strap and cutlery set. Microwave-safe.', 400, 'Eco Product', TRUE),
(gen_random_uuid(), 'Tree Planting Certificate', 'We plant a native Malaysian tree in your name and send you a digital certificate with GPS coordinates.', 600, 'Impact', TRUE),
(gen_random_uuid(), 'RM20 Shopee Voucher', 'Redeem RM20 off your next Shopee purchase.', 800, 'Voucher', TRUE),
(gen_random_uuid(), 'Zero Waste Starter Kit', 'Complete starter kit: bamboo toothbrush, straw set, beeswax wraps, tote bag, and seed bombs in a gift box.', 900, 'Bundle', TRUE);

-- ============================================================
-- CHALLENGES (daily and weekly)
-- ============================================================
DELETE FROM challenges;

INSERT INTO challenges (id, title, description, type, target, metric, xp_reward, eco_points_reward, badge, active) VALUES
-- Daily challenges
(gen_random_uuid(), 'First Recycle of the Day', 'Log your first recycling item of the day. Every journey starts with one step!', 'daily', 1, 'items_recycled', 50, 10, NULL, TRUE),
(gen_random_uuid(), 'Plastic Buster', 'Recycle at least 3 plastic items today. Beat plastic pollution one bottle at a time.', 'daily', 3, 'items_recycled', 80, 15, NULL, TRUE),
(gen_random_uuid(), 'Paper Saver', 'Recycle at least 2 kg of paper or cardboard today.', 'daily', 2, 'plastic_saved', 60, 10, NULL, TRUE),
(gen_random_uuid(), 'Streak Keeper', 'Maintain your recycling streak. Log at least one item to keep your streak alive!', 'daily', 1, 'streak_days', 30, 5, NULL, TRUE),
(gen_random_uuid(), 'E-Waste Warrior', 'Recycle at least 1 electronic item today. E-waste contains valuable materials!', 'daily', 1, 'items_recycled', 100, 20, NULL, TRUE),
(gen_random_uuid(), 'Metal Miner', 'Recycle at least 1 kg of metal/aluminium today.', 'daily', 1, 'plastic_saved', 70, 12, NULL, TRUE),
-- Weekly challenges
(gen_random_uuid(), 'Zero Waste Week', 'Recycle at least 10 items this week. Consistent effort makes a real difference!', 'weekly', 10, 'items_recycled', 200, 50, 'Recycling Novice', TRUE),
(gen_random_uuid(), 'Carbon Crusher', 'Reduce your carbon footprint by recycling 5 kg of materials this week.', 'weekly', 5, 'co2_reduced', 300, 60, 'Carbon Crusher', TRUE),
(gen_random_uuid(), 'Plastic-Free Champion', 'Recycle 10 plastic items this week. Malaysia aims to reduce 40% plastic waste by 2030!', 'weekly', 10, 'items_recycled', 250, 55, 'Plastic Champion', TRUE),
(gen_random_uuid(), 'Heavy Lifter', 'Recycle a total of 15 kg of materials this week. Every kg diverted from landfills counts!', 'weekly', 15, 'plastic_saved', 350, 80, 'Heavy Lifter', TRUE),
(gen_random_uuid(), 'Perfect Week', 'Log at least 1 item every day for 7 consecutive days. Consistency is key!', 'weekly', 7, 'streak_days', 500, 100, 'Perfect Week', TRUE),
(gen_random_uuid(), 'Eco Master', 'Recycle across at least 3 different material categories this week (plastic, paper, metal, glass, etc.)', 'weekly', 3, 'items_recycled', 400, 75, 'Eco Master', TRUE),
(gen_random_uuid(), 'Community Hero', 'Recycle 20 items this week and inspire others. Lead by example!', 'weekly', 20, 'items_recycled', 600, 120, 'Community Hero', TRUE);
